### ISSUE TITLE
OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by MrLinWang** [shinezyy/gem5_data_proc#8]
在大机房执行batch.py时会报OSError: [Errno 24] Too many open files
命令：
```bash
python batch.py -s /nfs/home/wanglulin/XiangShan-GEM5/GEM5/util/xs_scripts/example/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05-0-0-0 -t --topdown-raw -o /nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/results/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05/checkpoint-0-0-0.csv
```
具体log如下：
```bash
Process finished job: libquantum_19685
Traceback (most recent call last):
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 277, in <module>
/nfs/home/wanglulin/XiangShan-GEM5/GEM5/util/xs_scripts/example/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05-0-0-0/perlbench_diffmail_6/m5out/stats.txt
    main()
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 248, in main
    _ = [p.start() for p in jobs]
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 248, in <listcomp>
    _ = [p.start() for p in jobs]
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/context.py", line 224, in _Popen
Process finished job: namd_38493
    return _default_context.get_context().Process._Popen(process_obj)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/context.py", line 281, in _Popen
    return Popen(process_obj)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/popen_fork.py", line 65, in _launch
    child_r, parent_w = os.pipe()
OSError: [Errno 24] Too many open files
/nfs/home/wanglulin/XiangShan-GEM5/GEM5/util/xs_scripts/example/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05-0-0-0/zeusmp_15761/m5out/stats.txt
/nfs/home/wanglulin/XiangShan-GEM5/GEM5/util/xs_scripts/example/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05-0-0-0/libquantum_19685/m5out/stats.txt
Process Process-478:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
/nfs/home/wanglulin/XiangShan-GEM5/GEM5/util/xs_scripts/example/spec06_gcc15_rv64gcbv_O3_lto_base_nemu_single_core_NEMU_archgroup_2024-10-12-16-05-0-0-0/namd_38493/m5out/stats.txt
Process Process-475:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-491:
Process Process-481:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-480:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-488:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-490:
Process Process-485:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-486:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-492:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-497:
Process Process-493:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
FileNotFoundError: [Errno 2] No such file or directory
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-501:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-503:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-504:
Process Process-502:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-508:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Process Process-509:
Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 810, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/nfs/home/wanglulin/XiangShan-GEM5/gem5_data_proc/batch.py", line 244, in extract_and_post_process
    gloabl_dict[workload] = d
  File "<string>", line 2, in __setitem__
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 814, in _callmethod
    self._connect()
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/managers.py", line 801, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/nfs/home/wanglulin/miniconda3/envs/gem5/lib/python3.10/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by shinezyy** [comment]
![image](https://github.com/user-attachments/assets/538c373c-100d-4aab-960f-9d1f72af62b4)

**Comment by shinezyy** [comment]
![image](https://github.com/user-attachments/assets/f211322f-2caa-4cff-a574-3cebf8246cbb)

**Comment by MrLinWang** [comment]
感谢！
